
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 18 08:52:06 GMT-03:00 2026
//----------------------------------------------------

package parser;

import java_cup.runtime.*;
import erros.ListaErros;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Thu Jun 18 08:52:06 GMT-03:00 2026
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\121\000\002\002\010\000\002\002\004\000\002\002" +
    "\003\000\002\003\004\000\002\003\002\000\002\004\003" +
    "\000\002\004\010\000\002\004\007\000\002\005\004\000" +
    "\002\005\002\000\002\006\004\000\002\006\003\000\002" +
    "\010\003\000\002\010\003\000\002\007\013\000\002\012" +
    "\003\000\002\012\002\000\002\013\006\000\002\013\004" +
    "\000\002\011\004\000\002\011\002\000\002\016\004\000" +
    "\002\016\003\000\002\016\004\000\002\025\003\000\002" +
    "\025\003\000\002\025\003\000\002\025\003\000\002\025" +
    "\003\000\002\025\003\000\002\025\003\000\002\025\003" +
    "\000\002\033\007\000\002\034\007\000\002\034\011\000" +
    "\002\035\007\000\002\014\003\000\002\014\002\000\002" +
    "\015\005\000\002\015\003\000\002\026\012\000\002\026" +
    "\010\000\002\026\010\000\002\027\011\000\002\027\007" +
    "\000\002\027\007\000\002\036\006\000\002\036\002\000" +
    "\002\030\005\000\002\030\005\000\002\030\004\000\002" +
    "\031\005\000\002\031\005\000\002\032\003\000\002\032" +
    "\003\000\002\032\003\000\002\032\003\000\002\023\005" +
    "\000\002\023\003\000\002\017\004\000\002\017\006\000" +
    "\002\017\010\000\002\017\004\000\002\020\005\000\002" +
    "\020\005\000\002\020\004\000\002\020\003\000\002\022" +
    "\005\000\002\022\005\000\002\022\003\000\002\021\003" +
    "\000\002\021\006\000\002\021\003\000\002\021\005\000" +
    "\002\021\005\000\002\024\003\000\002\024\003\000\002" +
    "\024\003\000\002\024\003\000\002\024\003\000\002\024" +
    "\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\006\003\005\013\006\001\002\000\004\002" +
    "\256\001\002\000\004\002\uffff\001\002\000\004\044\007" +
    "\001\002\000\020\010\ufffd\011\ufffd\012\ufffd\017\ufffd\020" +
    "\ufffd\023\ufffd\044\ufffd\001\002\000\020\010\016\011\022" +
    "\012\020\017\017\020\021\023\012\044\013\001\002\000" +
    "\020\010\ufffc\011\ufffc\012\ufffc\017\ufffc\020\ufffc\023\ufffc" +
    "\044\ufffc\001\002\000\014\010\016\011\022\012\020\014" +
    "\075\044\013\001\002\000\004\044\uffc9\001\002\000\020" +
    "\010\ufffe\011\ufffe\012\ufffe\017\ufffe\020\ufffe\023\ufffe\044" +
    "\ufffe\001\002\000\004\044\067\001\002\000\004\044\uffcc" +
    "\001\002\000\012\010\016\011\022\012\020\044\013\001" +
    "\002\000\004\044\uffca\001\002\000\004\044\023\001\002" +
    "\000\004\044\uffcb\001\002\000\004\023\024\001\002\000" +
    "\014\010\ufff8\011\ufff8\012\ufff8\024\ufff8\044\ufff8\001\002" +
    "\000\014\010\016\011\022\012\020\024\027\044\013\001" +
    "\002\000\014\010\ufff9\011\ufff9\012\ufff9\024\ufff9\044\ufff9" +
    "\001\002\000\020\010\ufffa\011\ufffa\012\ufffa\017\ufffa\020" +
    "\ufffa\023\ufffa\044\ufffa\001\002\000\004\044\031\001\002" +
    "\000\004\042\032\001\002\000\012\021\041\031\037\043" +
    "\036\044\033\001\002\000\044\003\uffb9\021\057\022\uffb9" +
    "\023\uffb9\025\uffb9\026\uffb9\027\056\030\uffb9\031\uffb9\032" +
    "\uffb9\033\uffb9\034\uffb9\035\uffb9\036\uffb9\037\uffb9\040\uffb9" +
    "\041\uffb9\001\002\000\040\003\uffbc\022\uffbc\023\uffbc\025" +
    "\uffbc\026\uffbc\030\uffbc\031\uffbc\032\052\033\053\034\uffbc" +
    "\035\uffbc\036\uffbc\037\uffbc\040\uffbc\041\uffbc\001\002\000" +
    "\034\003\uffbf\022\uffbf\023\uffbf\025\uffbf\026\uffbf\030\uffbf" +
    "\031\uffbf\034\uffbf\035\uffbf\036\uffbf\037\uffbf\040\uffbf\041" +
    "\uffbf\001\002\000\040\003\uffbb\022\uffbb\023\uffbb\025\uffbb" +
    "\026\uffbb\030\uffbb\031\uffbb\032\uffbb\033\uffbb\034\uffbb\035" +
    "\uffbb\036\uffbb\037\uffbb\040\uffbb\041\uffbb\001\002\000\010" +
    "\021\041\043\036\044\033\001\002\000\010\025\050\030" +
    "\043\031\045\001\002\000\012\021\041\031\037\043\036" +
    "\044\033\001\002\000\010\022\044\030\043\031\045\001" +
    "\002\000\010\021\041\043\036\044\033\001\002\000\040" +
    "\003\uffb7\022\uffb7\023\uffb7\025\uffb7\026\uffb7\030\uffb7\031" +
    "\uffb7\032\uffb7\033\uffb7\034\uffb7\035\uffb7\036\uffb7\037\uffb7" +
    "\040\uffb7\041\uffb7\001\002\000\010\021\041\043\036\044" +
    "\033\001\002\000\034\003\uffc1\022\uffc1\023\uffc1\025\uffc1" +
    "\026\uffc1\030\uffc1\031\uffc1\034\uffc1\035\uffc1\036\uffc1\037" +
    "\uffc1\040\uffc1\041\uffc1\001\002\000\034\003\uffc2\022\uffc2" +
    "\023\uffc2\025\uffc2\026\uffc2\030\uffc2\031\uffc2\034\uffc2\035" +
    "\uffc2\036\uffc2\037\uffc2\040\uffc2\041\uffc2\001\002\000\020" +
    "\010\ufffb\011\ufffb\012\ufffb\017\ufffb\020\ufffb\023\ufffb\044" +
    "\ufffb\001\002\000\034\003\uffc0\022\uffc0\023\uffc0\025\uffc0" +
    "\026\uffc0\030\uffc0\031\uffc0\034\uffc0\035\uffc0\036\uffc0\037" +
    "\uffc0\040\uffc0\041\uffc0\001\002\000\010\021\041\043\036" +
    "\044\033\001\002\000\010\021\041\043\036\044\033\001" +
    "\002\000\034\003\uffbd\022\uffbd\023\uffbd\025\uffbd\026\uffbd" +
    "\030\uffbd\031\uffbd\034\uffbd\035\uffbd\036\uffbd\037\uffbd\040" +
    "\uffbd\041\uffbd\001\002\000\034\003\uffbe\022\uffbe\023\uffbe" +
    "\025\uffbe\026\uffbe\030\uffbe\031\uffbe\034\uffbe\035\uffbe\036" +
    "\uffbe\037\uffbe\040\uffbe\041\uffbe\001\002\000\004\044\066" +
    "\001\002\000\014\021\041\022\uffdc\031\037\043\036\044" +
    "\033\001\002\000\006\022\uffdd\026\064\001\002\000\004" +
    "\022\063\001\002\000\012\022\uffda\026\uffda\030\043\031" +
    "\045\001\002\000\040\003\uffba\022\uffba\023\uffba\025\uffba" +
    "\026\uffba\030\uffba\031\uffba\032\uffba\033\uffba\034\uffba\035" +
    "\uffba\036\uffba\037\uffba\040\uffba\041\uffba\001\002\000\012" +
    "\021\041\031\037\043\036\044\033\001\002\000\012\022" +
    "\uffdb\026\uffdb\030\043\031\045\001\002\000\040\003\uffb8" +
    "\022\uffb8\023\uffb8\025\uffb8\026\uffb8\030\uffb8\031\uffb8\032" +
    "\uffb8\033\uffb8\034\uffb8\035\uffb8\036\uffb8\037\uffb8\040\uffb8" +
    "\041\uffb8\001\002\000\006\003\071\025\070\001\002\000" +
    "\044\003\uffce\004\uffce\006\uffce\007\uffce\010\uffce\011\uffce" +
    "\012\uffce\015\uffce\016\uffce\017\uffce\020\uffce\021\uffce\023" +
    "\uffce\024\uffce\031\uffce\043\uffce\044\uffce\001\002\000\044" +
    "\003\uffcd\004\uffcd\006\uffcd\007\uffcd\010\uffcd\011\uffcd\012" +
    "\uffcd\015\uffcd\016\uffcd\017\uffcd\020\uffcd\021\uffcd\023\uffcd" +
    "\024\uffcd\031\uffcd\043\uffcd\044\uffcd\001\002\000\016\010" +
    "\ufff6\011\ufff6\012\ufff6\014\ufff6\024\ufff6\044\ufff6\001\002" +
    "\000\016\010\016\011\022\012\020\014\075\024\254\044" +
    "\013\001\002\000\004\044\077\001\002\000\004\044\ufff4" +
    "\001\002\000\004\044\ufff5\001\002\000\004\021\100\001" +
    "\002\000\014\010\016\011\022\012\020\022\ufff1\044\013" +
    "\001\002\000\006\022\ufff2\026\251\001\002\000\004\044" +
    "\250\001\002\000\004\022\104\001\002\000\014\010\uffed" +
    "\011\uffed\012\uffed\023\uffed\044\uffed\001\002\000\014\010" +
    "\016\011\022\012\020\023\107\044\013\001\002\000\014" +
    "\010\uffee\011\uffee\012\uffee\023\uffee\044\uffee\001\002\000" +
    "\034\003\125\004\112\006\121\007\124\010\016\011\022" +
    "\012\020\015\111\016\127\021\041\031\037\043\036\044" +
    "\115\001\002\000\010\025\247\030\043\031\045\001\002" +
    "\000\004\021\243\001\002\000\014\003\217\021\216\031" +
    "\037\043\036\044\033\001\002\000\036\003\uffe4\004\uffe4" +
    "\006\uffe4\007\uffe4\010\uffe4\011\uffe4\012\uffe4\015\uffe4\016" +
    "\uffe4\021\uffe4\024\uffe4\031\uffe4\043\uffe4\044\uffe4\001\002" +
    "\000\036\003\uffe9\004\uffe9\006\uffe9\007\uffe9\010\uffe9\011" +
    "\uffe9\012\uffe9\015\uffe9\016\uffe9\021\uffe9\024\uffe9\031\uffe9" +
    "\043\uffe9\044\uffe9\001\002\000\024\021\203\025\uffb9\027" +
    "\202\030\uffb9\031\uffb9\032\uffb9\033\uffb9\042\204\044\uffc9" +
    "\001\002\000\036\003\uffe7\004\uffe7\006\uffe7\007\uffe7\010" +
    "\uffe7\011\uffe7\012\uffe7\015\uffe7\016\uffe7\021\uffe7\024\uffe7" +
    "\031\uffe7\043\uffe7\044\uffe7\001\002\000\036\003\uffe8\004" +
    "\uffe8\006\uffe8\007\uffe8\010\uffe8\011\uffe8\012\uffe8\015\uffe8" +
    "\016\uffe8\021\uffe8\024\uffe8\031\uffe8\043\uffe8\044\uffe8\001" +
    "\002\000\036\003\uffe3\004\uffe3\006\uffe3\007\uffe3\010\uffe3" +
    "\011\uffe3\012\uffe3\015\uffe3\016\uffe3\021\uffe3\024\uffe3\031" +
    "\uffe3\043\uffe3\044\uffe3\001\002\000\014\003\153\021\152" +
    "\031\037\043\036\044\033\001\002\000\036\003\uffe5\004" +
    "\uffe5\006\uffe5\007\uffe5\010\uffe5\011\uffe5\012\uffe5\015\uffe5" +
    "\016\uffe5\021\uffe5\024\uffe5\031\uffe5\043\uffe5\044\uffe5\001" +
    "\002\000\036\003\uffe2\004\uffe2\006\uffe2\007\uffe2\010\uffe2" +
    "\011\uffe2\012\uffe2\015\uffe2\016\uffe2\021\uffe2\024\uffe2\031" +
    "\uffe2\043\uffe2\044\uffe2\001\002\000\014\003\146\021\041" +
    "\031\037\043\036\044\033\001\002\000\004\025\145\001" +
    "\002\000\036\003\142\004\112\006\121\007\124\010\016" +
    "\011\022\012\020\015\111\016\127\021\041\024\143\031" +
    "\037\043\036\044\115\001\002\000\004\021\132\001\002" +
    "\000\036\003\uffe6\004\uffe6\006\uffe6\007\uffe6\010\uffe6\011" +
    "\uffe6\012\uffe6\015\uffe6\016\uffe6\021\uffe6\024\uffe6\031\uffe6" +
    "\043\uffe6\044\uffe6\001\002\000\036\003\uffeb\004\uffeb\006" +
    "\uffeb\007\uffeb\010\uffeb\011\uffeb\012\uffeb\015\uffeb\016\uffeb" +
    "\021\uffeb\024\uffeb\031\uffeb\043\uffeb\044\uffeb\001\002\000" +
    "\004\044\133\001\002\000\006\022\134\027\135\001\002" +
    "\000\004\025\141\001\002\000\004\044\136\001\002\000" +
    "\004\022\137\001\002\000\004\025\140\001\002\000\036" +
    "\003\uffdf\004\uffdf\006\uffdf\007\uffdf\010\uffdf\011\uffdf\012" +
    "\uffdf\015\uffdf\016\uffdf\021\uffdf\024\uffdf\031\uffdf\043\uffdf" +
    "\044\uffdf\001\002\000\036\003\uffe0\004\uffe0\006\uffe0\007" +
    "\uffe0\010\uffe0\011\uffe0\012\uffe0\015\uffe0\016\uffe0\021\uffe0" +
    "\024\uffe0\031\uffe0\043\uffe0\044\uffe0\001\002\000\040\003" +
    "\uffea\004\uffea\006\uffea\007\uffea\010\uffea\011\uffea\012\uffea" +
    "\015\uffea\016\uffea\021\uffea\024\uffea\025\145\031\uffea\043" +
    "\uffea\044\uffea\001\002\000\016\010\ufff3\011\ufff3\012\ufff3" +
    "\014\ufff3\024\ufff3\044\ufff3\001\002\000\036\003\uffec\004" +
    "\uffec\006\uffec\007\uffec\010\uffec\011\uffec\012\uffec\015\uffec" +
    "\016\uffec\021\uffec\024\uffec\031\uffec\043\uffec\044\uffec\001" +
    "\002\000\036\003\uffc3\004\uffc3\006\uffc3\007\uffc3\010\uffc3" +
    "\011\uffc3\012\uffc3\015\uffc3\016\uffc3\021\uffc3\024\uffc3\031" +
    "\uffc3\043\uffc3\044\uffc3\001\002\000\036\003\uffcf\004\uffcf" +
    "\006\uffcf\007\uffcf\010\uffcf\011\uffcf\012\uffcf\015\uffcf\016" +
    "\uffcf\021\uffcf\024\uffcf\031\uffcf\043\uffcf\044\uffcf\001\002" +
    "\000\012\003\151\025\150\030\043\031\045\001\002\000" +
    "\036\003\uffd1\004\uffd1\006\uffd1\007\uffd1\010\uffd1\011\uffd1" +
    "\012\uffd1\015\uffd1\016\uffd1\021\uffd1\024\uffd1\031\uffd1\043" +
    "\uffd1\044\uffd1\001\002\000\036\003\uffd0\004\uffd0\006\uffd0" +
    "\007\uffd0\010\uffd0\011\uffd0\012\uffd0\015\uffd0\016\uffd0\021" +
    "\uffd0\024\uffd0\031\uffd0\043\uffd0\044\uffd0\001\002\000\012" +
    "\021\041\031\037\043\036\044\033\001\002\000\004\023" +
    "\171\001\002\000\024\023\uffc7\030\043\031\045\034\162" +
    "\035\163\036\165\037\161\040\166\041\164\001\002\000" +
    "\004\023\156\001\002\000\034\003\125\004\112\006\121" +
    "\007\124\010\016\011\022\012\020\015\111\016\127\021" +
    "\041\031\037\043\036\044\115\001\002\000\036\003\142" +
    "\004\112\006\121\007\124\010\016\011\022\012\020\015" +
    "\111\016\127\021\041\024\160\031\037\043\036\044\115" +
    "\001\002\000\036\003\uffd5\004\uffd5\006\uffd5\007\uffd5\010" +
    "\uffd5\011\uffd5\012\uffd5\015\uffd5\016\uffd5\021\uffd5\024\uffd5" +
    "\031\uffd5\043\uffd5\044\uffd5\001\002\000\012\021\uffb3\031" +
    "\uffb3\043\uffb3\044\uffb3\001\002\000\012\021\uffb6\031\uffb6" +
    "\043\uffb6\044\uffb6\001\002\000\012\021\uffb5\031\uffb5\043" +
    "\uffb5\044\uffb5\001\002\000\012\021\uffb1\031\uffb1\043\uffb1" +
    "\044\uffb1\001\002\000\012\021\uffb4\031\uffb4\043\uffb4\044" +
    "\uffb4\001\002\000\012\021\uffb2\031\uffb2\043\uffb2\044\uffb2" +
    "\001\002\000\012\021\041\031\037\043\036\044\033\001" +
    "\002\000\012\022\uffc8\023\uffc8\030\043\031\045\001\002" +
    "\000\034\003\125\004\112\006\121\007\124\010\016\011" +
    "\022\012\020\015\111\016\127\021\041\031\037\043\036" +
    "\044\115\001\002\000\036\003\142\004\112\006\121\007" +
    "\124\010\016\011\022\012\020\015\111\016\127\021\041" +
    "\024\173\031\037\043\036\044\115\001\002\000\036\003" +
    "\uffd4\004\uffd4\006\uffd4\007\uffd4\010\uffd4\011\uffd4\012\uffd4" +
    "\015\uffd4\016\uffd4\021\uffd4\024\uffd4\031\uffd4\043\uffd4\044" +
    "\uffd4\001\002\000\004\022\176\001\002\000\024\022\044" +
    "\030\043\031\045\034\162\035\163\036\165\037\161\040" +
    "\166\041\164\001\002\000\004\023\177\001\002\000\034" +
    "\003\125\004\112\006\121\007\124\010\016\011\022\012" +
    "\020\015\111\016\127\021\041\031\037\043\036\044\115" +
    "\001\002\000\036\003\142\004\112\006\121\007\124\010" +
    "\016\011\022\012\020\015\111\016\127\021\041\024\201" +
    "\031\037\043\036\044\115\001\002\000\036\003\uffd6\004" +
    "\uffd6\006\uffd6\007\uffd6\010\uffd6\011\uffd6\012\uffd6\015\uffd6" +
    "\016\uffd6\021\uffd6\024\uffd6\031\uffd6\043\uffd6\044\uffd6\001" +
    "\002\000\004\044\212\001\002\000\014\021\041\022\uffdc" +
    "\031\037\043\036\044\033\001\002\000\012\021\041\031" +
    "\037\043\036\044\033\001\002\000\010\025\206\030\043" +
    "\031\045\001\002\000\036\003\uffc5\004\uffc5\006\uffc5\007" +
    "\uffc5\010\uffc5\011\uffc5\012\uffc5\015\uffc5\016\uffc5\021\uffc5" +
    "\024\uffc5\031\uffc5\043\uffc5\044\uffc5\001\002\000\004\022" +
    "\210\001\002\000\014\025\211\030\uffba\031\uffba\032\uffba" +
    "\033\uffba\001\002\000\036\003\uffde\004\uffde\006\uffde\007" +
    "\uffde\010\uffde\011\uffde\012\uffde\015\uffde\016\uffde\021\uffde" +
    "\024\uffde\031\uffde\043\uffde\044\uffde\001\002\000\016\025" +
    "\uffb8\030\uffb8\031\uffb8\032\uffb8\033\uffb8\042\213\001\002" +
    "\000\012\021\041\031\037\043\036\044\033\001\002\000" +
    "\010\025\215\030\043\031\045\001\002\000\036\003\uffc4" +
    "\004\uffc4\006\uffc4\007\uffc4\010\uffc4\011\uffc4\012\uffc4\015" +
    "\uffc4\016\uffc4\021\uffc4\024\uffc4\031\uffc4\043\uffc4\044\uffc4" +
    "\001\002\000\012\021\041\031\037\043\036\044\033\001" +
    "\002\000\004\023\231\001\002\000\004\023\221\001\002" +
    "\000\034\003\125\004\112\006\121\007\124\010\016\011" +
    "\022\012\020\015\111\016\127\021\041\031\037\043\036" +
    "\044\115\001\002\000\036\003\142\004\112\006\121\007" +
    "\124\010\016\011\022\012\020\015\111\016\127\021\041" +
    "\024\223\031\037\043\036\044\115\001\002\000\040\003" +
    "\uffd2\004\uffd2\005\224\006\uffd2\007\uffd2\010\uffd2\011\uffd2" +
    "\012\uffd2\015\uffd2\016\uffd2\021\uffd2\024\uffd2\031\uffd2\043" +
    "\uffd2\044\uffd2\001\002\000\004\023\226\001\002\000\036" +
    "\003\uffd8\004\uffd8\006\uffd8\007\uffd8\010\uffd8\011\uffd8\012" +
    "\uffd8\015\uffd8\016\uffd8\021\uffd8\024\uffd8\031\uffd8\043\uffd8" +
    "\044\uffd8\001\002\000\034\003\125\004\112\006\121\007" +
    "\124\010\016\011\022\012\020\015\111\016\127\021\041" +
    "\031\037\043\036\044\115\001\002\000\036\003\142\004" +
    "\112\006\121\007\124\010\016\011\022\012\020\015\111" +
    "\016\127\021\041\024\230\031\037\043\036\044\115\001" +
    "\002\000\036\003\uffd3\004\uffd3\006\uffd3\007\uffd3\010\uffd3" +
    "\011\uffd3\012\uffd3\015\uffd3\016\uffd3\021\uffd3\024\uffd3\031" +
    "\uffd3\043\uffd3\044\uffd3\001\002\000\034\003\125\004\112" +
    "\006\121\007\124\010\016\011\022\012\020\015\111\016" +
    "\127\021\041\031\037\043\036\044\115\001\002\000\036" +
    "\003\142\004\112\006\121\007\124\010\016\011\022\012" +
    "\020\015\111\016\127\021\041\024\233\031\037\043\036" +
    "\044\115\001\002\000\040\003\uffd2\004\uffd2\005\224\006" +
    "\uffd2\007\uffd2\010\uffd2\011\uffd2\012\uffd2\015\uffd2\016\uffd2" +
    "\021\uffd2\024\uffd2\031\uffd2\043\uffd2\044\uffd2\001\002\000" +
    "\036\003\uffd7\004\uffd7\006\uffd7\007\uffd7\010\uffd7\011\uffd7" +
    "\012\uffd7\015\uffd7\016\uffd7\021\uffd7\024\uffd7\031\uffd7\043" +
    "\uffd7\044\uffd7\001\002\000\004\022\236\001\002\000\004" +
    "\023\237\001\002\000\034\003\125\004\112\006\121\007" +
    "\124\010\016\011\022\012\020\015\111\016\127\021\041" +
    "\031\037\043\036\044\115\001\002\000\036\003\142\004" +
    "\112\006\121\007\124\010\016\011\022\012\020\015\111" +
    "\016\127\021\041\024\241\031\037\043\036\044\115\001" +
    "\002\000\040\003\uffd2\004\uffd2\005\224\006\uffd2\007\uffd2" +
    "\010\uffd2\011\uffd2\012\uffd2\015\uffd2\016\uffd2\021\uffd2\024" +
    "\uffd2\031\uffd2\043\uffd2\044\uffd2\001\002\000\036\003\uffd9" +
    "\004\uffd9\006\uffd9\007\uffd9\010\uffd9\011\uffd9\012\uffd9\015" +
    "\uffd9\016\uffd9\021\uffd9\024\uffd9\031\uffd9\043\uffd9\044\uffd9" +
    "\001\002\000\012\021\041\031\037\043\036\044\033\001" +
    "\002\000\010\022\245\030\043\031\045\001\002\000\004" +
    "\025\246\001\002\000\036\003\uffe1\004\uffe1\006\uffe1\007" +
    "\uffe1\010\uffe1\011\uffe1\012\uffe1\015\uffe1\016\uffe1\021\uffe1" +
    "\024\uffe1\031\uffe1\043\uffe1\044\uffe1\001\002\000\036\003" +
    "\uffc6\004\uffc6\006\uffc6\007\uffc6\010\uffc6\011\uffc6\012\uffc6" +
    "\015\uffc6\016\uffc6\021\uffc6\024\uffc6\031\uffc6\043\uffc6\044" +
    "\uffc6\001\002\000\006\022\uffef\026\uffef\001\002\000\012" +
    "\010\016\011\022\012\020\044\013\001\002\000\004\044" +
    "\253\001\002\000\006\022\ufff0\026\ufff0\001\002\000\004" +
    "\002\001\001\002\000\016\010\ufff7\011\ufff7\012\ufff7\014" +
    "\ufff7\024\ufff7\044\ufff7\001\002\000\004\002\000\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\254\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\003\007\001\001" +
    "\000\010\004\013\031\010\032\014\001\001\000\002\001" +
    "\001\000\012\006\072\007\071\010\073\032\075\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\032\027\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\005\024\001\001\000\006\031\025\032\014\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\020\037\021\033\022\034\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\021\033\022\050\001\001\000\002" +
    "\001\001\000\010\020\041\021\033\022\034\001\001\000" +
    "\002\001\001\000\006\021\033\022\046\001\001\000\002" +
    "\001\001\000\006\021\033\022\045\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\021\033\022\054\001\001\000\006\021\033\022" +
    "\053\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\014\060\015\057\020\061\021\033\022" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\020\064\021\033\022" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\007\254\010\073\032\075\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\010\012\102\013\100\032\101\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\011" +
    "\104\001\001\000\006\031\105\032\014\001\001\000\002" +
    "\001\001\000\036\016\125\017\113\020\107\021\033\022" +
    "\034\025\130\026\127\027\121\030\116\031\115\032\014" +
    "\033\112\034\117\035\122\001\001\000\002\001\001\000" +
    "\002\001\001\000\012\020\153\021\033\022\034\023\217" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\012\020\153\021\033\022\034\023\154\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\020\146\021\033" +
    "\022\034\001\001\000\002\001\001\000\034\017\113\020" +
    "\107\021\033\022\034\025\143\026\127\027\121\030\116" +
    "\031\115\032\014\033\112\034\117\035\122\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\020" +
    "\174\021\033\022\034\023\173\001\001\000\002\001\001" +
    "\000\004\024\166\001\001\000\002\001\001\000\036\016" +
    "\156\017\113\020\107\021\033\022\034\025\130\026\127" +
    "\027\121\030\116\031\115\032\014\033\112\034\117\035" +
    "\122\001\001\000\034\017\113\020\107\021\033\022\034" +
    "\025\143\026\127\027\121\030\116\031\115\032\014\033" +
    "\112\034\117\035\122\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\020\167" +
    "\021\033\022\034\001\001\000\002\001\001\000\036\016" +
    "\171\017\113\020\107\021\033\022\034\025\130\026\127" +
    "\027\121\030\116\031\115\032\014\033\112\034\117\035" +
    "\122\001\001\000\034\017\113\020\107\021\033\022\034" +
    "\025\143\026\127\027\121\030\116\031\115\032\014\033" +
    "\112\034\117\035\122\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\024\166\001\001\000\002\001\001\000" +
    "\036\016\177\017\113\020\107\021\033\022\034\025\130" +
    "\026\127\027\121\030\116\031\115\032\014\033\112\034" +
    "\117\035\122\001\001\000\034\017\113\020\107\021\033" +
    "\022\034\025\143\026\127\027\121\030\116\031\115\032" +
    "\014\033\112\034\117\035\122\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\014\206\015\057\020\061\021" +
    "\033\022\034\001\001\000\010\020\204\021\033\022\034" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\020\213\021\033\022\034\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\020\174\021\033\022\034" +
    "\023\234\001\001\000\002\001\001\000\002\001\001\000" +
    "\036\016\221\017\113\020\107\021\033\022\034\025\130" +
    "\026\127\027\121\030\116\031\115\032\014\033\112\034" +
    "\117\035\122\001\001\000\034\017\113\020\107\021\033" +
    "\022\034\025\143\026\127\027\121\030\116\031\115\032" +
    "\014\033\112\034\117\035\122\001\001\000\004\036\224" +
    "\001\001\000\002\001\001\000\002\001\001\000\036\016" +
    "\226\017\113\020\107\021\033\022\034\025\130\026\127" +
    "\027\121\030\116\031\115\032\014\033\112\034\117\035" +
    "\122\001\001\000\034\017\113\020\107\021\033\022\034" +
    "\025\143\026\127\027\121\030\116\031\115\032\014\033" +
    "\112\034\117\035\122\001\001\000\002\001\001\000\036" +
    "\016\231\017\113\020\107\021\033\022\034\025\130\026" +
    "\127\027\121\030\116\031\115\032\014\033\112\034\117" +
    "\035\122\001\001\000\034\017\113\020\107\021\033\022" +
    "\034\025\143\026\127\027\121\030\116\031\115\032\014" +
    "\033\112\034\117\035\122\001\001\000\004\036\233\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\036\016\237\017\113\020\107\021\033\022\034\025" +
    "\130\026\127\027\121\030\116\031\115\032\014\033\112" +
    "\034\117\035\122\001\001\000\034\017\113\020\107\021" +
    "\033\022\034\025\143\026\127\027\121\030\116\031\115" +
    "\032\014\033\112\034\117\035\122\001\001\000\004\036" +
    "\241\001\001\000\002\001\001\000\010\020\243\021\033" +
    "\022\034\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\032\251\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void syntax_error(Symbol s){ }

    public void unrecovered_syntax_error(Symbol cur_token){ }

    public void defineErro(int linha, int coluna, String texto) {
        scanner.Scanner sc = (scanner.Scanner) this.getScanner();
        sc.defineErro(linha, coluna, texto);
    }

    public void defineErro(int linha, int coluna){
        scanner.Scanner sc = (scanner.Scanner) this.getScanner();
        sc.defineErro(linha, coluna);
    }

    public void defineErro(String texto){
        scanner.Scanner sc = (scanner.Scanner) this.getScanner();
        sc.defineErro(texto);
    }

    protected int error_sync_size() { return 1; }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {
  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // op_Relacional ::= DIF 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_Relacional",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // op_Relacional ::= IGUALIGUAL 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_Relacional",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // op_Relacional ::= MENORIGUAL 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_Relacional",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // op_Relacional ::= MAIORIGUAL 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_Relacional",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // op_Relacional ::= MENOR 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_Relacional",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // op_Relacional ::= MAIOR 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("op_Relacional",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // factor ::= ABREPAR expr FECHAPAR 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = e; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // factor ::= ID PONTO ID 
            {
              Double RESULT =null;
		 RESULT = 0.0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // factor ::= ID 
            {
              Double RESULT =null;
		 RESULT = 0.0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // factor ::= ID ABREPAR arg_list_opt FECHAPAR 
            {
              Double RESULT =null;
		 RESULT = 0.0; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // factor ::= NUMBER 
            {
              Double RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double n = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = n; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("factor",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // term ::= factor 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // term ::= factor DIV term 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f / t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // term ::= factor MULT term 
            {
              Double RESULT =null;
		int fleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int fright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double f = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = f * t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("term",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // expr ::= term 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // expr ::= MENOS term 
            {
              Double RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = -t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expr ::= expr MENOS term 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e - t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expr ::= expr MAIS term 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double t = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = e + t; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expr_ptv ::= error PTVIRG 
            {
              Double RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 parser.defineErro(kleft, kright, "Comando ou expressão incompleta"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expr_ptv ::= ID PONTO ID ATRIB expr PTVIRG 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expr_ptv ::= ID ATRIB expr PTVIRG 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expr_ptv ::= expr PTVIRG 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_ptv",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // condicao ::= expr 
            {
              Double RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double e = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 parser.defineErro(eleft, eright, "Condição sem operador relacional - ex: if (x)"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // condicao ::= expr op_Relacional expr 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("condicao",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // tipo ::= ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // tipo ::= KW_FLOAT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // tipo ::= KW_DOUBLE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // tipo ::= KW_INT 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // declaracao ::= tipo ID error 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 parser.defineErro(kleft, kright, "Declaração de variável sem ponto e vírgula"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // declaracao ::= tipo ID PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracao",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // comando_return ::= KW_RETURN error 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 parser.defineErro(kleft, kright, "return sem ponto e vírgula"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_return",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // comando_return ::= KW_RETURN expr error 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		 parser.defineErro(kleft, kright, "return sem ponto e vírgula"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_return",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // comando_return ::= KW_RETURN expr PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_return",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // else ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // else ::= KW_ELSE ABRECHAVE expr_list FECHACHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("else",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // comando_while ::= KW_WHILE error ABRECHAVE expr_list FECHACHAVE 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 parser.defineErro(kleft, kright, "WHILE sem parênteses na condição"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_while",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // comando_while ::= KW_WHILE condicao ABRECHAVE expr_list FECHACHAVE 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		 parser.defineErro(kleft, kright, "WHILE sem parênteses na condição"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_while",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // comando_while ::= KW_WHILE ABREPAR condicao FECHAPAR ABRECHAVE expr_list FECHACHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_while",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // comando_if ::= KW_IF error ABRECHAVE expr_list FECHACHAVE else 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		 parser.defineErro(kleft, kright, "IF sem parênteses na condição"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_if",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // comando_if ::= KW_IF condicao ABRECHAVE expr_list FECHACHAVE else 
            {
              Object RESULT =null;
		int kleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int kright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Object k = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		 parser.defineErro(kleft, kright, "IF sem parênteses na condição"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_if",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // comando_if ::= KW_IF ABREPAR condicao FECHAPAR ABRECHAVE expr_list FECHACHAVE else 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_if",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // arg_list ::= expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // arg_list ::= arg_list VIRGULA expr 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // arg_list_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list_opt",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // arg_list_opt ::= arg_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("arg_list_opt",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // comando_call ::= ID ABREPAR arg_list_opt FECHAPAR PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_call",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // comando_read ::= KW_READ ABREPAR ID PONTO ID FECHAPAR PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_read",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // comando_read ::= KW_READ ABREPAR ID FECHAPAR PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_read",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // comando_print ::= KW_PRINT ABREPAR expr FECHAPAR PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando_print",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // comando ::= comando_call 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // comando ::= comando_read 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // comando ::= comando_print 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // comando ::= comando_while 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // comando ::= comando_if 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // comando ::= declaracao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // comando ::= comando_return 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // comando ::= expr_ptv 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("comando",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // expr_list ::= expr_list error 
            {
              Double RESULT =null;
		 /* Sincronização automática para não perder o IF/WHILE */ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // expr_list ::= comando 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // expr_list ::= expr_list comando 
            {
              Double RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expr_list",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // decl_list_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_list_opt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // decl_list_opt ::= decl_list_opt declaracao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl_list_opt",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // param_list ::= tipo ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // param_list ::= param_list VIRGULA tipo ID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // param_list_opt ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list_opt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // param_list_opt ::= param_list 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("param_list_opt",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // func ::= func_tipo ID ABREPAR param_list_opt FECHAPAR decl_list_opt ABRECHAVE expr_list FECHACHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // func_tipo ::= KW_VOID 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func_tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // func_tipo ::= tipo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func_tipo",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // func_list ::= func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func_list",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // func_list ::= func_list func 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("func_list",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // field_list ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("field_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // field_list ::= field_list declaracao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("field_list",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // decl ::= KW_CLASS ID ABRECHAVE field_list FECHACHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // decl ::= KW_FINAL tipo ID ATRIB expr PTVIRG 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // decl ::= declaracao 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("decl",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // top_decls ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("top_decls",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // top_decls ::= top_decls decl 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("top_decls",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // programa ::= error 
            {
              Object RESULT =null;
		 parser.defineErro("Erro no bloco principal do programa"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // programa ::= KW_PROGRAM ID top_decls ABRECHAVE func_list FECHACHAVE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

