
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 18 08:52:06 GMT-03:00 2026
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 23;
  public static final int IGUALIGUAL = 30;
  public static final int MENOR = 27;
  public static final int PTVIRG = 19;
  public static final int KW_FINAL = 13;
  public static final int KW_PRINT = 11;
  public static final int MENORIGUAL = 29;
  public static final int KW_IF = 2;
  public static final int MAIORIGUAL = 28;
  public static final int PONTO = 21;
  public static final int ABREPAR = 15;
  public static final int ID = 34;
  public static final int ATRIB = 32;
  public static final int VIRGULA = 20;
  public static final int MAIS = 22;
  public static final int KW_CLASS = 14;
  public static final int ABRECHAVE = 17;
  public static final int NUMBER = 33;
  public static final int MULT = 24;
  public static final int EOF = 0;
  public static final int KW_WHILE = 4;
  public static final int DIV = 25;
  public static final int KW_RETURN = 5;
  public static final int MAIOR = 26;
  public static final int error = 1;
  public static final int FECHACHAVE = 18;
  public static final int KW_VOID = 10;
  public static final int FECHAPAR = 16;
  public static final int KW_DOUBLE = 7;
  public static final int KW_PROGRAM = 9;
  public static final int KW_READ = 12;
  public static final int KW_ELSE = 3;
  public static final int KW_FLOAT = 8;
  public static final int DIF = 31;
  public static final int KW_INT = 6;
}

